### ISSUE TITLE
there is only wrong imsi numbers

### ISSUE THREAD

**Issue by aleen42** [Oros42/IMSI-catcher#1]
- When I use the condition: `p[71:][:2]=='\x08\x29'` and `p[62:][:2]=='\x08\x29'`, I have get no any imsi numbers output, and I think I have set the correct frequency.
- When I use a condition: `p[71:][:2]=='\x08\x49'` and `p[62:][:2]=='\x08\x49'`, there are some numbers output on the screen, but they all do not belong to any devices I want to track. So what can I do with this catcher?

**Comment by Oros42** [comment]
Sorry, I'm not en expert in GSM and I have test it only on a french network.  
But first step to investigate is to use wireshark :  
```
sudo wireshark -k -Y '!icmp && gsmtap' -i lo
```
And if you can send me a wireshark capture, it would be useful to debug.

**Comment by aleen42** [comment]
So, May I ask you a question, and can I also get IMEI from the gsm package?

**Comment by Oros42** [comment]
Ooh IMEI and ISMI are not the same thing.
ISMI is used to identify the user (SIM card). It's not link to the phone https://en.wikipedia.org/wiki/International_mobile_subscriber_identity
IMEI is a number to identify the phone. And it's not link to the SIM https://en.wikipedia.org/wiki/IMEI

In my wireshark sniffing, I've never seen IMEI.

**Comment by aleen42** [comment]
According to some suggestions, IMEI may not be transmitted with GSM packages and of course we won't get this number in the sniffed package, unless the situation that service providers has asked phones for IMEI. :cry:

**Comment by Oros42** [comment]
Yes.
You can found your own ISMI number to track your phone but it's not easy.
This is how I process : 
1- check that your phone use GSM (2G) network
2- run gqrx (http://gqrx.dk/)
3- with your phone phone, call a second phone and find which frequency is used to upload (phone to antenna, around 876Mhz to 914Mhz)
4- if you get the frequency, add an offset of 45Mhz (ex : 880Mhz->924Mhz)
5- use this frequency with my program and «normally», you will have your ISMI in the list of ISMI found.
6- repeat step 1 to 5 in other network area and check if you have see a common number in the list

good luck

**Comment by aleen42** [comment]
Ok, I'll check your process and see whether it's okay, Thx.

**Comment by stenroot** [comment]
Hello, today published an updated program in GNU Radio release v3.7.10.1, how to you can add your IMSI-Catcher?

**Comment by Oros42** [comment]
Sorry, I don't understand this part "how to you can add your IMSI-Catcher" :-/

**Comment by SenseProg** [comment]
Hi, 

 

We need UHF reader with radius-polarisations, up 30 db/m transmit power, up 6-10 m (minimum 5) recommend read range, frequency range -- 860Mhz-875Mhz . With four ports for ANT.

And also we need UHF reader with around (radius) polarisations antenna  up 9 dbi. 

Their size must be up 250x250. 

Must be readed 200-300 tags in one moment. 

 

Can you propose something? 

 

Thank you very much for answers!

 

Best regards, 

 

Bogdan Parfenyuk, 

Embedded developer,

SenseSystems

**Comment by Oros42** [comment]
Wooow WTF?
I have just made this script for fun with the USB DVB-T key RTL2832U. I didn't sell anything.

**Comment by aleen42** [comment]
:-), WTF, an ad email?

**Comment by stenroot** [comment]
Hello I'm using GNU Radio v3.7.10.1(http://gnuradio.org/news/gnu-radio-v3-7-10-1-release/) installed on the USB, how to add your IMSI-Catcher?

**Comment by Oros42** [comment]
Mmmh I haven't try to setup GNU Radio without using pybombs :-/

**Comment by Oros42** [comment]
@stenroot : I have found a new way to setup gr-gsm :
```
sudo add-apt-repository -y ppa:ptrkrysik/gr-gsm
sudo apt update
sudo apt install gr-gsm python-numpy python-scipy python-scapy
```

**Comment by Oros42** [comment]
I have made some fixes in the code.

**Comment by SonyKucing** [comment]
i am in indonesia with MCC : 510 and MNC : 10
where code is to edit for correct imsi catcher ?

**Comment by Oros42** [comment]
MCC and MNC are store in mcc-mnc/mcc_codes.json
mcc-mnc/update_codes.py is used to update mcc-mnc/mcc_codes.json with data from https://en.wikipedia.org/wiki/Mobile_Network_Code

**Comment by SonyKucing** [comment]
work perfectly bro... thanks for update your code...

**Comment by onoff0** [comment]
perfect, I can find many IMSI, but also forcing my cell phone in 2G mode I can not find my IMSI. I also tried to analyze with wireshark on the downlink frequency of my phone but nothing. you have ideas?

**Comment by aleen42** [comment]
@onoff0 This catcher will always lose some IMSIs, when it's not included in GSM headers. According to some experts, IMSIs won't be transferred between phones and base stations after the connection at the first time. Therefore, I advise you to try to force to break the connection between them, so that phones can transfer IMSIs again to reconnect.

**Comment by Oros42** [comment]
@onoff0 You should check if 2G and 3G use the same frequency.

**Comment by onoff0** [comment]
thanks for the answers. I make some tests I noticed that the phone in GSM mode when LAC changes or switching on can wait for an update. Just then an SMS to force the network to request a location update, and then take its IMSI.

**Comment by onoff0** [comment]
it would be possible to implement the catcher for TMSI, with a grouping counter of unique values? thanks !!

**Comment by Oros42** [comment]
Work in progress for TMSI since last week ;-)
Coming soon.

**Comment by onoff0** [comment]
great !!! good job ;)

**Comment by aleen42** [comment]
@onoff0 During forcing network to request a location update, IMSIs will be transferred in the GSM package?

**Comment by onoff0** [comment]
@aleen42 Yes, 
personally I have only tried it with phones in GSM. with wireshark you can see in detail the network packets received from mobile phones under a specific frequency assigned by the telephone operators. The IMSIs newly assigned (change LAC, telephone turned on, location update) will be visible in wireshark via a paging request, after which the network will assign to mobile phones in the same area a TMSI that will remain so for some time.

**Comment by Oros42** [comment]
Hello everyone !
I have add the display of TMSI ! :-)
And bonus, you can filter IMSIs and follow one special IMSI by using this :
```
sudo python IMSI-TMSI-catcher.py -m "123 45 6789101112"
```
or
```
sudo python IMSI-TMSI-catcher.py -m 123456789101112
```

**Comment by onoff0** [comment]
great, I'm trying.
I do not mean a lot of programming, it would be possible to implement a function that picks up only the TMSI in a given frequency with the possibility to filter only those that repeat more. example, only displays the TMSI that is repeated in 'area for more than 3 or 4 times ++.
Congratulations for your work!

**Comment by stevevaius** [comment]
Hi, for an NGO project, we are looking a way to determine the number of mobile cells around a radius. We need to count the unique mobiles via detecting their IMSI or something unique. Your tool looks like built for it. How we can implement? Any help appreciated!

**Comment by Oros42** [comment]
@onoff0 : If you displays the TMSI that is repeated X times, you can't have a live TMSI tracking. You should wait X time to sniff GSM network and after that, count each TMSI.
I have thinking about filtering one TMSI. But It's not easy. The TMSI could change during the time.

@stevevaius : The variable nb_IMSI already count the number of unique IMSIs (column 1). But I don't known yet how to count mobiles that haven't send IMSI and use only TMSI.

**Comment by rdarioc** [comment]
Guys, I am impressed by the quality of your work. @Oros42 , is it possible, based on your experience, to access the SS7 network of the mobile operator? My main concern is privacy (geolocation and packet sniffing and decoding) and I am wondering if we need to worry ONLY from the improper use of the SS7 protocols accessed by an hub provided by the mobile operator or if we should ALSO worry from an "anonymous" access done with this type of technology. Thank you. p.s. I understand this may not be the right place for this conversation and I apologize for it, so please, move this message where it more appropriately fits.

**Comment by Oros42** [comment]
Thanks you @rdarioc :-)
This issue is more like a topic than a true issue XD
I'm sorry, I don't know yet who does SS7 works but I want to learn it !
I need documentation about SS7.

**Comment by rdarioc** [comment]
Ask, and you shall receive: 

Signalling System #7, ITU-T Q.700 series:
http://www.itu.int/rec/T-REC-Q/e

Mobile Application Part (MAP) specification, 3GPP TS 29.002:
http://www.3gpp.org/ftp/Specs/archive/29_series/29.002/

Study into routeing of MT-SMs via the HPLMN, 3GPP TR 23.840:
http://www.3gpp.org/ftp/Specs/archive/23_series/23.840/

Support of Optimal Routeing (SOR), 3GPP TS 23.079:
http://www.3gpp.org/ftp/Specs/archive/23_series/23.079/

[25c3-locating-mobile-phones.pdf](https://github.com/Oros42/IMSI-catcher/files/612111/25c3-locating-mobile-phones.pdf)

**Comment by Oros42** [comment]
Ooh thanks :-D

**Comment by habibur333** [comment]
Is it possible to retrieve phone numbers or MSIN  from IMSI numbers?

**Comment by Oros42** [comment]
You can't have the phone number but you have MSIN in the IMSI number.
MSIN is the last part of the IMSI.
https://en.wikipedia.org/wiki/International_mobile_subscriber_identity

**Comment by habibur333** [comment]
Thanks Oros42 for your fast response. here is 2 issue
1st issue:
I am trying to collect phone number from air. is there any way to collect them? 
2nd issue
from this link https://en.wikipedia.org/wiki/International_mobile_subscriber_identity  For Bangladesh the  MSIN  number and phone number is same not sure for other countries. at present there is no such type of imsi number in Bangladesh for grammin phone which exampled in wiki.

**Comment by Oros42** [comment]
If it's true that MSIN number and phone number is same in Bangladesh then my IMSI-catcher got it !
In my country (France), the phone number is not in the MSIN.

**Comment by BlackPhreaker** [comment]
Good day ... In my opinion it would be nice to add the output log !!!

**Comment by Oros42** [comment]
Hello
You can do this :
```sh
sudo -s
python IMSI-TMSI-catcher.py > log.csv&
tail -f log.csv
```
;-)

**Comment by BlackPhreaker** [comment]
It is possible and so I agree !!! But I was referring to the script, with the date and time ...

**Comment by Oros42** [comment]
This ?
```
date > log.csv
python IMSI-TMSI-catcher.py >> log.csv&
tail -f log.csv
```
:-D

**Comment by BlackPhreaker** [comment]
Perhaps esle Could you be able to help me here in this example ...

***
def write_log(x):
	file_object = open("./gsm.log", "a+")
	try:
		file_object.write(x)
	finally:
		file_object.close()
***

Not like it is impossible to add to your script ((

**Comment by Oros42** [comment]
Add your function in my code and change «print» to «write_log» at lines 172, 174 and 185.

**Comment by BlackPhreaker** [comment]
I can not do ... But still does not work ... Check please !!!

***
#!/usr/bin/python
# -*- coding: utf-8 -*-

import time
from scapy.all import sniff
import json
from optparse import OptionParser

imsis=[] # [IMSI,...]
tmsis={} # {TMSI:IMSI,...}
nb_IMSI=0 # count the number of IMSI

# Log Start
def write_log(x):
file_object = open("./gsm.log", "a+")
try:
file_object.write(x)
finally:
file_object.close()
# Log End

# return something like '0xd9605460'
def str_tmsi(tmsi):
	if tmsi != "":
		new_tmsi="0x"
		for a in tmsi:
			c=hex(ord(a))
			if len(c)==4:
				new_tmsi+=str(c[2])+str(c[3])
			else:
				new_tmsi+="0"+str(c[2])
		return new_tmsi
	else:
		return ""

# return something like '208 20 1752XXXXXX ; France ; Bouygues ; Bouygues Telecom'
def str_imsi(imsi, p=""):
	new_imsi=''
	for a in imsi:
		c=hex(ord(a))
		if len(c)==4:
			new_imsi+=str(c[3])+str(c[2])
		else:
			new_imsi+=str(c[2])+"0"
	
	mcc=new_imsi[1:4]
	mnc=new_imsi[4:6]
	country=""
	brand=""
	operator=""
	if mcc in mcc_codes:
		if mnc in mcc_codes[mcc]['MNC']:
			country=mcc_codes[mcc]['c'][0]
			brand=mcc_codes[mcc]['MNC'][mnc][0]
			operator=mcc_codes[mcc]['MNC'][mnc][1]
			new_imsi=mcc+" "+mnc+" "+new_imsi[6:]
		elif mnc+new_imsi[6:7] in mcc_codes[mcc]['MNC']:
			mnc+=new_imsi[6:7]
			country=mcc_codes[mcc]['c'][0]
			brand=mcc_codes[mcc]['MNC'][mnc][0]
			operator=mcc_codes[mcc]['MNC'][mnc][1]
			new_imsi=mcc+" "+mnc+" "+new_imsi[7:]
		else:
			country=mcc_codes[mcc]['c'][0]
			brand="Unknown"
			operator=mcc_codes[mcc]['MNC'][mnc][1]
			new_imsi=mcc+" "+mnc+" "+new_imsi[6:]

	try:
		m="{:17s} ; {} ; {} ; {}".format(new_imsi, country.encode('utf-8'), brand.encode('utf-8'), operator.encode('utf-8'))
	except:
		m=""
		print("Error", p, new_imsi, country, brand, operator)
	return m

# print TMSI, IMSI and operator's information
def show_imsi(imsi1="", imsi2="", tmsi1="", tmsi2="", p=""):
	global imsis
	global tmsis
	global nb_IMSI

	do_print=False
	n=''
	if imsi1 and (not imsi_to_track or imsi1 == imsi_to_track):
		if imsi1 not in imsis:
			# new IMSI
			do_print=True
			imsis.append(imsi1)
			nb_IMSI+=1
			n=nb_IMSI
		if tmsi1 and (tmsi1 not in tmsis or tmsis[tmsi1] != imsi1):
			# new TMSI to an ISMI
			do_print=True
			tmsis[tmsi1]=imsi1
		if tmsi2 and (tmsi2 not in tmsis or tmsis[tmsi2] != imsi1):
			# new TMSI to an ISMI
			do_print=True
			tmsis[tmsi2]=imsi1		
	
	if imsi2 and (not imsi_to_track or imsi2 == imsi_to_track):
		if imsi2 not in imsis:
			# new IMSI
			do_print=True
			imsis.append(imsi2)
			nb_IMSI+=1
			n=nb_IMSI
		if tmsi1 and (tmsi1 not in tmsis or tmsis[tmsi1] != imsi2):
			# new TMSI to an ISMI
			do_print=True
			tmsis[tmsi1]=imsi2
		if tmsi2 and (tmsi2 not in tmsis or tmsis[tmsi2] != imsi2):
			# new TMSI to an ISMI
			do_print=True
			tmsis[tmsi2]=imsi2

	if not imsi1 and not imsi2 and tmsi1 and tmsi2:
		if tmsi2 in tmsis:
			# switch the TMSI
			do_print=True
			imsi1=tmsis[tmsi2]
			tmsis[tmsi1]=imsi1
			del tmsis[tmsi2]

	if do_print:
		if imsi1:
			#print("{:7s} ; {:10s} ; {:10s} ; {}".format(str(n), str_tmsi(tmsi1), str_tmsi(tmsi2), str_imsi(imsi1, p)))
			write_log("{:7s} ; {:10s} ; {:10s} ; {}".format(str(n), str_tmsi(tmsi1), str_tmsi(tmsi2), str_imsi(imsi1, p)))
		if imsi2:
			#print("{:7s} ; {:10s} ; {:10s} ; {}".format(str(n), str_tmsi(tmsi1), str_tmsi(tmsi2), str_imsi(imsi2, p)))
			write_log("{:7s} ; {:10s} ; {:10s} ; {}".format(str(n), str_tmsi(tmsi1), str_tmsi(tmsi2), str_imsi(imsi2, p)))

	if not imsi1 and not imsi2 and show_all_tmsi:
		do_print=False
		if tmsi1 and tmsi1 not in tmsis:
			do_print=True
			tmsis[tmsi1]=""
		if tmsi1 and tmsi1 not in tmsis:
			do_print=True
			tmsis[tmsi2]=""
		if do_print:
			#print("{:7s} ; {:10s} ; {:10s} ; {}".format(str(n), str_tmsi(tmsi1), str_tmsi(tmsi2), "; ; ;"))
			write_log("{:7s} ; {:10s} ; {:10s} ; {}".format(str(n), str_tmsi(tmsi1), str_tmsi(tmsi2), "; ; ;"))


def find_imsi(x):
	p=str(x)
	if ord(p[0x36]) != 0x1: # Channel Type != BCCH (0)
		tmsi1=""
		tmsi2=""
		imsi1=""
		imsi2=""
		if ord(p[0x3c]) == 0x21: # Message Type: Paging Request Type 1
			if ord(p[0x3e]) == 0x08 and (ord(p[0x3f]) & 0x1) == 0x1: # Channel 1: TCH/F (Full rate) (2)
				# Mobile Identity 1 Type: IMSI (1)
				"""
				        0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
				0000   00 00 00 00 00 00 00 00 00 00 00 00 08 00 45 00
				0010   00 43 1c d4 40 00 40 11 1f d4 7f 00 00 01 7f 00
				0020   00 01 c2 e4 12 79 00 2f fe 42 02 04 01 00 00 00
				0030   c9 00 00 16 21 26 02 00 07 00 31 06 21 00 08 XX
				0040   XX XX XX XX XX XX XX 2b 2b 2b 2b 2b 2b 2b 2b 2b
				0050   2b
				XX XX XX XX XX XX XX XX = IMSI
				"""
				imsi1=p[0x3f:][:8]
				# ord(p[0x3a]) == 0x59 = l2 pseudo length value: 22
				if ord(p[0x3a]) == 0x59 and ord(p[0x48]) == 0x08 and (ord(p[0x49]) & 0x1) == 0x1: # Channel 2: TCH/F (Full rate) (2)
					# Mobile Identity 2 Type: IMSI (1)
					"""
				        0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
				0000   00 00 00 00 00 00 00 00 00 00 00 00 08 00 45 00
				0010   00 43 90 95 40 00 40 11 ac 12 7f 00 00 01 7f 00
				0020   00 01 b4 1c 12 79 00 2f fe 42 02 04 01 00 00 00
				0030   c8 00 00 16 51 c6 02 00 08 00 59 06 21 00 08 YY
				0040   YY YY YY YY YY YY YY 17 08 XX XX XX XX XX XX XX
				0050   XX
				YY YY YY YY YY YY YY YY = IMSI 1
				XX XX XX XX XX XX XX XX = IMSI 2
					"""
					imsi2=p[0x49:][:8]
				elif ord(p[0x3a]) == 0x59 and ord(p[0x48]) == 0x08 and (ord(p[0x49]) & 0x1) == 0x1: # Channel 2: TCH/F (Full rate) (2)
					# Mobile Identity - Mobile Identity 2 - IMSI
					"""
				        0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
				0000   00 00 00 00 00 00 00 00 00 00 00 00 08 00 45 00
				0010   00 43 f6 92 40 00 40 11 46 15 7f 00 00 01 7f 00
				0020   00 01 ab c1 12 79 00 2f fe 42 02 04 01 00 00 00
				0030   d8 00 00 23 3e be 02 00 05 00 4d 06 21 a0 08 YY
				0040   YY YY YY YY YY YY YY 17 05 f4 XX XX XX XX 2b 2b
				0050   2b
				YY YY YY YY YY YY YY YY = IMSI 1
				XX XX XX XX = TMSI
					"""
					tmsi1=p[0x4a:][:4]

				show_imsi(imsi1, imsi2, tmsi1, tmsi2, p)

			elif ord(p[0x45]) == 0x08 and (ord(p[0x46]) & 0x1) == 0x1: # Channel 2: TCH/F (Full rate) (2)
				# Mobile Identity 2 Type: IMSI (1)
				"""
				        0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
				0000   00 00 00 00 00 00 00 00 00 00 00 00 08 00 45 00
				0010   00 43 57 8e 40 00 40 11 e5 19 7f 00 00 01 7f 00
				0020   00 01 99 d4 12 79 00 2f fe 42 02 04 01 00 00 00
				0030   c7 00 00 11 05 99 02 00 03 00 4d 06 21 00 05 f4
				0040   yy yy yy yy 17 08 XX XX XX XX XX XX XX XX 2b 2b
				0050   2b
				yy yy yy yy = TMSI/P-TMSI - Mobile Identity 1
				XX XX XX XX XX XX XX XX = IMSI
				"""
				tmsi1=p[0x40:][:4]
				imsi2=p[0x46:][:8]
				show_imsi(imsi1, imsi2, tmsi1, tmsi2, p)

			elif ord(p[0x3e]) == 0x05 and (ord(p[0x3f]) & 0x07) == 4: # Mobile Identity - Mobile Identity 1 - TMSI/P-TMSI 
				"""
				        0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
				0000   00 00 00 00 00 00 00 00 00 00 00 00 08 00 45 00
				0010   00 43 b3 f7 40 00 40 11 88 b0 7f 00 00 01 7f 00
				0020   00 01 ce 50 12 79 00 2f fe 42 02 04 01 00 03 fd
				0030   d1 00 00 1b 03 5e 05 00 00 00 41 06 21 00 05 f4
				0040   XX XX XX XX 17 05 f4 YY YY YY YY 2b 2b 2b 2b 2b
				0050   2b
				XX XX XX XX = TMSI/P-TMSI - Mobile Identity 1
				YY YY YY YY = TMSI/P-TMSI - Mobile Identity 2
				"""
				tmsi1=p[0x40:][:4]
				if ord(p[0x45]) == 0x05 and (ord(p[0x46]) & 0x07) == 4: # Mobile Identity - Mobile Identity 2 - TMSI/P-TMSI 
					tmsi2=p[0x47:][:4]
				else:
					tmsi2=""

				show_imsi(imsi1, imsi2, tmsi1, tmsi2, p)

		elif ord(p[0x3c]) == 0x22: # Message Type: Paging Request Type 2
			if ord(p[0x47]) == 0x08 and (ord(p[0x48]) & 0x1) == 0x1: # Mobile Identity 3 Type: IMSI (1)
				"""
				        0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f				
				0000   00 00 00 00 00 00 00 00 00 00 00 00 08 00 45 00
				0010   00 43 1c a6 40 00 40 11 20 02 7f 00 00 01 7f 00
				0020   00 01 c2 e4 12 79 00 2f fe 42 02 04 01 00 00 00
				0030   c9 00 00 16 20 e3 02 00 04 00 55 06 22 00 yy yy
				0040   yy yy zz zz zz 4e 17 08 XX XX XX XX XX XX XX XX
				0050   8b
				yy yy yy yy = TMSI/P-TMSI - Mobile Identity 1
				zz zz zz zz = TMSI/P-TMSI - Mobile Identity 2
				XX XX XX XX XX XX XX XX = IMSI
				"""
				tmsi1=p[0x3e:][:4]
				tmsi2=p[0x42:][:4]
				imsi2=p[0x48:][:8]
				show_imsi(imsi1, imsi2, tmsi1, tmsi2, p)


parser = OptionParser(usage="%prog: [options]")
parser.add_option("-a", "--alltmsi", action="store_true", dest="show_all_tmsi", help="Show TMSI who haven't got IMSI (default  : false)")
parser.add_option("-i", "--iface", dest="iface", default="lo", help="Interface (default : lo)")
parser.add_option("-m", "--imsi", dest="imsi", default="", type="string", help='IMSI to track (default : None, Example: 123456789101112 or "123 45 6789101112")')
parser.add_option("-p", "--port", dest="port", default="4729", type="int", help="Port (default : 4729)")
(options, args) = parser.parse_args()

show_all_tmsi=options.show_all_tmsi
imsi_to_track=""
if options.imsi:
	imsi="9"+options.imsi.replace(" ", "")
	for i in range(0,15,2):
		imsi_to_track+=chr(int(imsi[i+1])*16+int(imsi[i]))

# mcc codes form https://en.wikipedia.org/wiki/Mobile_Network_Code
with open('mcc-mnc/mcc_codes.json', 'r') as file:
	mcc_codes = json.load(file)

print("{:7s} ; {:10s} ; {:10s} ; {:17s} ; {} ; {} ; {}".format("Nb IMSI", "TMSI-1", "TMSI-2", "IMSI", "country", "brand", "operator"))
sniff(iface=options.iface, filter="port {} and not icmp and udp".format(options.port), prn=find_imsi, store=0)

write_log(str(time.time()) + '\n')

***

**Comment by BlackPhreaker** [comment]
Can add your script log many think it will come in handy in the future ... For Rania sposibo for pomasch !!!

**Comment by Oros42** [comment]
You need to indent your code.
This :
```python
# Log Start
def write_log(x):
file_object = open("./gsm.log", "a+")
try:
file_object.write(x)
finally:
file_object.close()
# Log End
```
should be :
```python
# Log Start
def write_log(x):
    file_object = open("./gsm.log", "a+")
    try:
    file_object.write(x)
    finally:
    file_object.close()
# Log End
```

Sorry, but I'm not sure to understand your last message :-s

**Comment by BlackPhreaker** [comment]
I mean ... Thank you for helping me ...

**Comment by Oros42** [comment]
Okay ;-)

**Comment by BlackPhreaker** [comment]
Currently tuning a script ... If you want I can send you then that ye have put him at ???

**Comment by BlackPhreaker** [comment]
Hi Oros42 !!! Thank you for your previous help ... There was such Problem I can not add on your display example (LAC) and (CID) ... Esle Could you not mogliby help ???

**Comment by Oros42** [comment]
Oooh yes, I've got a script for that. I clean it and publish it soon ;-)

**Comment by BlackPhreaker** [comment]
It has helped me very much ... Thank you'll be waiting !!!

**Comment by Oros42** [comment]
I've add find_cell_id.py and immediate_assignment_catcher.py.
Could you try it?

**Comment by BlackPhreaker** [comment]
Thank you very much ... your code works perfectly !!! I hope I have for your example will create a script with the final conclusion ...

===================================================================
Nb IMSI ; TMSI-1     ; TMSI-2     ; IMSI     ; Country    ; Brand ; Operator  ; MCC   ; MNC ;  LAC   ; CID    ;
===================================================================

**Comment by BlackPhreaker** [comment]
And also add the output ARFCN MHz dBm and all this in one script!!!

**Comment by BlackPhreaker** [comment]
Oooh There was a lot of problems combining pre script ... It's a pity I will do next

**Comment by BlackPhreaker** [comment]
Tell me what I am doing wrong ???

https://github.com/BlackPhreaker/GSM/blob/master/IMSI_Catcher_Ver1.0.7.py

**Comment by BlackPhreaker** [comment]
The head has burst !!!

**Comment by Oros42** [comment]
Oooh yes ARFCN in MHz....
Need to write this https://en.wikipedia.org/wiki/ARFCN in python.

For your code, lac and cell are not defined in show_imsi() (lines 172 and 175).

In find_imsi() lines 198 and 199 can't works. It's need «Channel Type: BCCH (1)» (ord(p[0x36]) == 0x01) and «Message Type: System Information Type 3» (ord(p[0x3c]) == 0x1b).

This days, I don't have time to work more on my IMSI-Cather :-/

**Comment by BlackPhreaker** [comment]
Thanks for the tips !!! I will try to cope myself ...

**Comment by BlackPhreaker** [comment]
I will try to combine 3 of your script in one esle out ... Thank you for your time on me

**Comment by Oros42** [comment]
I've thinking about it but it's not simple.
The point who block me is «which ISMI/T-IMSI is affected to the timeslot».
I recommend you to run wireshark to check what append.
Good luck.

**Comment by richblackhat** [comment]
got this error bro , all other .py working fine but as soon it detects traffic bum goes like this 
WARNING: No route found for IPv6 destination :: (no default route?)
MCC   ; MNC  ; LAC   ; CellId ; Country ; Brand ; Operator
Traceback (most recent call last):
  File "find_cell_id.py", line 88, in <module>
    sniff(iface=options.iface, filter="port {} and not icmp and udp".format(options.port), prn=find_cell, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 586, in sniff
    r = prn(p)
  File "find_cell_id.py", line 75, in find_cell
    operator=mcc_codes[mcc]['MNC'][mnc][1]
KeyError: '05'

**Comment by Oros42** [comment]
Oooh yes, need a «elif» line 72.
Could you show me the content of the «Channel Type: BCCH (1), Message Type: System Information Type 3» like lines 17 to 23. Use wireshark for this.
