### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by MaxVasilev** [Oros42/IMSI-catcher#106]
Добрый день, так как все же осуществлять запись в базу данных mysql?
Что должен содержать env файл, как должна быть настроена сама база данных, нужно ли что-то менять в самом коде simple_IMSI-Catcher?

**Comment by purwowd** [comment]
Read this line:
https://github.com/Oros42/IMSI-catcher/blob/6bcf2c7a1e701fc5f33da9f46ebe4c518aeef579/simple_IMSI-catcher.py#L163

**Comment by MaxVasilev** [comment]
Это все замечательно, но как и где правильно создать env файл, чтобы начать запись в mysql? 
И почему перед imsi  появилась 9?
