### ISSUE TITLE
???

### ISSUE THREAD

**Issue by BlackPhreaker** [Oros42/IMSI-catcher#13]
Hello ... Is it possible to search the first 5 characters (python simple IMSI-catcher.by -m 25007**********) ???

**Comment by beeprime** [comment]
It gives "string index out of range" error

**Comment by BlackPhreaker** [comment]
I understood this ... I thought someone can help fix it ???

**Comment by Oros42** [comment]
Tell me what you think of my update.

**Comment by BlackPhreaker** [comment]
Hi!!! Thanks for the help... I'll finish the rest for myself !!!
