### ISSUE TITLE
How to track IMSI using --imsi="xxx xx xxxxxxxxxx"

### ISSUE THREAD

**Issue by yasirmaqsood** [Oros42/IMSI-catcher#132]
Hi,
I am trying to track an IMSI by using --imsi="xxx xx xxxxxxxxxx" but it does not track . Does it work without using livemon? because when I run livemon with this argument, it gives an error that "Address is already in use" and without using livemon it does not start scanning. Kindly help on how to track an IMSI.

**Comment by Oros42** [comment]
You should add the option `sniff` : `--sniff --imsi="xxx xx xxxxxxxxxx"`

**Comment by yasirmaqsood** [comment]
Thanks alot for your help
