### ISSUE TITLE
Work with 5G? Or need higher freq antenna?

### ISSUE THREAD

**Issue by windowshopr** [Oros42/IMSI-catcher#150]
Might be a newbie question here, but came across this repo and love the idea of getting into software based antennas, however where I live, GSM isn’t a very popular cellular technology. It’s all 5G and LTE around here. Would this repo work (theoretically) if I had a 5G capable antenna to work with? It’s my understanding that 5G operates at between like 28-39 GHz? Just a thought, I did a search for 5G and LTE in the existing issues but didn’t find anything. Thanks!

**Comment by Oros42** [comment]
No, it's impossible because gr-gsm didn't support 5G.
