### ISSUE TITLE
windows version available?

### ISSUE THREAD

**Issue by blul1ghtz** [Oros42/IMSI-catcher#165]
when i run "simple_IMSI-catcher.py -s" it tells me that theres no interface "lo" then i change it to localhost and it tells me theres no interface "localhost" what do i do or where do i get a working windows version of this?

**Comment by Oros42** [comment]
Have you try to add `-i <your_local_interface>` ?
I don't have Windows. So I can't help you more.

**Comment by blul1ghtz** [comment]
i couldn't find a way to get the interface name on windows and i wasn't too sure about if the name on sdr# panel is the interface name :/ i can close this if you want me to.
