### ISSUE TITLE
option to search for specific one

### ISSUE THREAD

**Issue by bourla77** [Oros42/IMSI-catcher#37]
Hi is it possible to continuously search for specific imsi?
i saw in the code an empty line for it, is it working?
Thanks.  
Im trying to find my phone in the list.

**Comment by Oros42** [comment]
> Hi is it possible to continuously search for specific imsi?
Yes, it's possible

> i saw in the code an empty line for it, is it working?
What ? Where exactly you see an empty line ?

> Im trying to find my phone in the list.
Not easy. I'm trying to write an help for that. But not finish

**Comment by bourla77** [comment]
Not empty you are right ,
"imsi to track" ?
I'm new to python
