### ISSUE TITLE
Do I need to buy a tuner too?

### ISSUE THREAD

**Issue by Micolocobr2** [Oros42/IMSI-catcher#44]
Hi,

Great software you have here!!
I want to use this software to find 850mhz cell numbers.
Do I need to buy a tuner to use with RTL2832U or its just plug this hardware and run your software on ubuntu?

This dongle based on RTL2832U is good to run IMSI Captcher?
https://goo.gl/KLcP6J

Very thanks in advance

Marcelo

**Comment by Oros42** [comment]
Hello
Like the picture in your link, you just have to plug this hardware and run the software :-)

**Comment by Micolocobr2** [comment]
Yes!! great sw at all!!

Even more simple to use than I thought.
