### ISSUE TITLE
find_cell_id.py  UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 5: ordinal not in range(128)

### ISSUE THREAD

**Issue by oscarmh** [Oros42/IMSI-catcher#5]
Hi, when executing find_cell I got an error, will yoy please tellme how to correct it ? Thanks !!

**Comment by Oros42** [comment]
I have made a fix. Does it solve the error?

**Comment by oscarmh** [comment]
Like a charm :-) thanks a lot !!
