### ISSUE TITLE
Can this be used for marketing?

### ISSUE THREAD

**Issue by kkar** [Oros42/IMSI-catcher#50]
Hello! Great project! Can this be used for in-store proximity marketing as well?

**Comment by FFY00** [comment]
Yes but please be aware that any use outside a test environment would be highly ilegal.

**Comment by FFY00** [comment]
No, you have the instructions you need in the readme.

**Comment by kkar** [comment]
No need to be offensive here @FFY00 I am just asking for guidance since I never touched the project in the past. At least, is it possible to achieve this with RTL2832U or do I need something more capable, like HackRF?

**Comment by Oros42** [comment]
Did you really read the [README.md](https://github.com/Oros42/IMSI-catcher/blob/master/README.md) ?
```
[...]
1 USB DVB-T key (RTL2832U) with antenna (less than 15$) or a OsmocomBB phone or HackRF
[...]
```
You can choose RTL2832U or HackRF or a OsmocomBB phone.
XD

**Comment by FFY00** [comment]
Sorry, I wasn't trying to be offensive. You have all the information you need in the readme assuming you are running a debian based operating system. If you are running other os, I can give you some instructions. And an RTL2832U will work just fine.

**Comment by kkar** [comment]
@Oros42 yes i did, but my question was about broadcasting suggestions, not just picking the surrounding IMSIs, that's why i asked for RTL. @FFY00 thank you.

**Comment by kkar** [comment]
@Oros42 thank you. I am trying to find information on how can I broadcast an SMS on nearby devices (for short range, like 10m or something), for in-store SMS marketing campaigns. All Bluetooth solutions are way too old for this goal. I was asking if this is possible with simple_IMSI-catcher.

**Comment by Oros42** [comment]
No, you can't with simple_IMSI-catcher.
It only listen.

**Comment by kkar** [comment]
Thank you @Oros42 !!!
