### ISSUE TITLE
Question |  does it open a bts?

### ISSUE THREAD

**Issue by kolet** [Oros42/IMSI-catcher#61]
hey there @Oros42 

quick question, does ur code / grgsm_livemon  open a new BTS ?  or just listing the air ?

Do phones /handset/device gets connected to our device  for example USB DVB-T key (RTL2832U) or it just listing to the wireless signals (like wifi on an open network)

cheers

**Comment by Oros42** [comment]
Hello
It's a passive system. So no transmission and it only listening the air.

**Comment by kolet** [comment]
thanks alot :) 👍
