### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by aawheatley** [Oros42/IMSI-catcher#62]
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2200012

I get this error when running **grgsm_livemon** and don't know how to fix it.

**Comment by Oros42** [comment]
I'm not the author of gr-gsm. So ask to Piotr Krysik (https://github.com/ptrkrysik/gr-gsm).

**Comment by aawheatley** [comment]
Sorry and Thanks!
