### ISSUE TITLE
why not 

### ISSUE THREAD

**Issue by root0day** [Oros42/IMSI-catcher#70]
![Screenshot from 2019-03-31 13-56-48](https://user-images.githubusercontent.com/26130494/55290109-43ece100-53be-11e9-8e47-69d7309fbb51.png)
![Screenshot from 2019-03-31 14-01-04](https://user-images.githubusercontent.com/26130494/55290110-494a2b80-53be-11e9-9750-fb9f375ae5cd.png)
![Screenshot from 2019-03-31 14-01-37](https://user-images.githubusercontent.com/26130494/55290111-49e2c200-53be-11e9-831d-36a2cb15d902.png)
![Uploading Screenshot from 2019-03-31 14-01-51.png…]()

can you tell me how to solve this probiem?
not a conmputer majior
please

**Comment by root0day** [comment]
root@ubuntu:/home/ubuntu# uname -a
Linux ubuntu 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:/home/ubuntu#

**Comment by Oros42** [comment]
For Ubuntu 18.04, remove ptrkrysik's repository and take a look to https://osmocom.org/projects/gr-gsm/wiki/Installation
