### ISSUE TITLE
IMSI run but cant read data from gr gsm 

### ISSUE THREAD

**Issue by asyooty249** [Oros42/IMSI-catcher#79]
![new](https://user-images.githubusercontent.com/59701704/72088577-87945400-331b-11ea-8047-d1d4d46774f1.png)
dears 
need your help why IMSi cant read the data from gr gsm as you can see in the picture the ge gsm have data but i cant see it in IMSI
any advice to solve the issue

**Comment by asyooty249** [comment]
dears 

thanks for your support i had fix the issue but now is no showing the phone number in the IMSI .

**Comment by asyooty249** [comment]
![samenumber](https://user-images.githubusercontent.com/59701704/72100649-0b5a3a80-3334-11ea-9b50-a15f56ea1af2.png)
same issue

**Comment by tombaki** [comment]
@asyooty249 
i'v same issue but i canno't get any data from console what did u do to fix that
root@kali:~/imsi/imsi# ./simple_IMSI-catcher.py --sniff
Nb IMSI ; TMSI-1     ; TMSI-2     ; IMSI              ; country      ; brand      ; operator              ; MCC  ; MNC   ; LAC    ; CellId ; Timestamp

**Comment by Oros42** [comment]
No data == no IMSI send by the cell tower.
Try to change the frequency

Cell Id take few seconds to update.
