### ISSUE TITLE
Feature Request: Adding sniffing on uplink for IMSI attach

### ISSUE THREAD

**Issue by Irdev110** [Oros42/IMSI-catcher#80]
Hello,
Would it be possible to add support for sniffing uplink IMSI attach requests (identity response from MS to tower)?
https://en.wikipedia.org/wiki/GSM_procedures#IMSI_attach

**Comment by Oros42** [comment]
Perhaps
My program is base on gr-gsm. And it seem that it can do it (https://github.com/ptrkrysik/gr-gsm/issues/94).
But I didn't have to time for working on the implementation in my IMSI-catcher.
