### ISSUE TITLE
cannot run grgsm_livemon -f xxx.xM

### ISSUE THREAD

**Issue by brahmanggi** [Oros42/IMSI-catcher#84]
hello,
I've got this kind of error below :

> Warning: failed to XInitThreads()
[INFO] [UHD] linux; GNU C++ version 8.2.0; Boost_106700; UHD_3.13.1.0-3
gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.13.4
built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Detached kernel driver
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Exact sample rate is: 2000000.052982 Hz
[R82XX] PLL not locked!
Traceback (most recent call last):
  File "/usr/local/bin/grgsm_livemon", line 361, in <module>
    main()
  File "/usr/local/bin/grgsm_livemon", line 349, in main
    tb = top_block_cls(args=options.args, collector=options.collector, collectorport=options.collectorport, fc=options.fc, gain=options.gain, osr=options.osr, ppm=options.ppm, samp_rate=options.samp_rate, serverport=options.serverport, shiftoff=options.shiftoff)
  File "/usr/local/bin/grgsm_livemon", line 180, in __init__
    self.blocks_socket_pdu_0_0 = blocks.socket_pdu("UDP_SERVER", '127.0.0.1', serverport, 10000, False)
  File "/usr/lib/python2.7/dist-packages/gnuradio/blocks/blocks_swig5.py", line 1063, in make
    return _blocks_swig5.socket_pdu_make(type, addr, port, MTU, tcp_no_delay)
RuntimeError: bind: Address already in use

Already check the server port there are no port 10000 turns out there no services using that port,

thank you

**Comment by Oros42** [comment]
The README.md say :
```
With an old version of gr-gsm
-----------------------------
  
Open 2 terminals.  
In terminal 1

sudo python3 simple_IMSI-catcher.py --sniff
```
