### ISSUE TITLE
Unable to locate package gr-gsm

### ISSUE THREAD

**Issue by Andrew151515** [Oros42/IMSI-catcher#85]
How to use IMSI catcher if it is not possible to install gr-gsm

root@pc:~/IMSI-catcher# apt install gr-gsm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gr-gsm

**Comment by Oros42** [comment]
Read https://osmocom.org/projects/gr-gsm/wiki/Installation
