### ISSUE TITLE
meterpreter timeout

### ISSUE THREAD

**Issue by u1o2** [Oros42/IMSI-catcher#94]
why? I connect when the opposite computer opens my trojan but when I type the command it gives a timeout error.

like this:

[*] Started HTTP reverse handler on http://XX.XX.XX
ls   
[*] http://XX.XX.XX handling request from XX.XX.XX; (UUID: ubcurexs) Staging x86 payload (181337 bytes) ...
[*] Meterpreter session 1 opened (XX.XX.XX -> XX.XX.XX.) at 2020-04-18 08:27:24 -0400

meterpreter > ls
[-] Error running command ls: Rex::TimeoutError Operation timed out.
meterpreter > ls

[-] Error running command ls: Rex::TimeoutError Operation timed out.
meterpreter >

**Comment by Oros42** [comment]
Wrong place for this.
