### ISSUE TITLE
Calls and SMS

### ISSUE THREAD

**Issue by netw4r** [Oros42/IMSI-catcher#96]
Hey I’m wondering if using this code with a ‘NooElec NESDR Mini’ can allow me to intercept calls and SMS? If not, what kind of radio would I need for this? Will this code allow for it , or does this code just work for displaying the IMSIs?

**Comment by Oros42** [comment]
No. My code only displaying the IMSIs.
Take a look to grgsm_decode (part of gr-gsm).
