### ISSUE TITLE
Intercepting calls

### ISSUE THREAD

**Issue by netw4r** [Oros42/IMSI-catcher#98]
Hello I am a researcher and I’m looking to be able to intercept calls. Just for my own experimental purposes only. I want to see if it can be done essentially. I am new here, I apologize for my newbie-ness. You told me to look at **grgsm_decode (part of gr-gsm)**., I cannot find this anywhere, wondering if you could possibly elaborate? Thank you.

**Comment by Oros42** [comment]
Install gr-gsm and read the documentation of grgsm_decode.
I'm not the author of gr-gsm
